@startuml

!theme amiga

hide empty members

class Account  {
  account_id
  district_id
  frequency
  date
}

class Card {
  card_id
  disp_id
  type
  issued
}

class Client {
  client_id
  birth_number
  district_id
}

class Disposition {
  disp_id
  client_id
  account_id
  type
}

class District {
  code
  name
  region
  "no. of municipalities with inhabitants < 499"
  "no. of municipalities with inhabitants 500-1999"
  "no. of municipalities with inhabitants 2000-9999"
  "no. of municipalities with inhabitants >10000"
  "no. of cities"
  "ratio of urban inhabitants"
  "average salary"
  "unemploymant rate '95"
  "unemploymant rate '96"
  "no. of enterpreneurs per 1000 inhabitants"
  "no. of commited crimes '95"
  "no. of commited crimes '96"
}

class Loan {
  loan_id
  account_id
  date
  amount
  duration
  payments
  status
}

class Transactions {
  trans_id
  account_id
  date
  type
  operation
  amount
  balance
  k_symbol
  bank
  account
}

Loan "0..1" --  Account
Transactions "*" -- Account

District -right- Client
Disposition -- Client
Account -left- District
Account -right- "1..*" Disposition

Disposition -right- Card

@enduml
